CREATE PROC FI_SP_AltBeneficiario
    @ID            BIGINT,
    @NOME          VARCHAR (50),
	@CPF           VARCHAR (14),
	@IDCLIENTE     BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		CPF = @CPF,
		NOME = @NOME,
		IDCLIENTE = @IDCLIENTE
	WHERE ID = @ID
END