CREATE PROC FI_SP_PesqBeneficiario
	@campoOrdenacao varchar(200),
	@crescente bit	
AS
BEGIN
	DECLARE @SCRIPT NVARCHAR(MAX)
	DECLARE @ORDER VARCHAR(50)
	
	SET @ORDER = ' NOME '

	IF(@crescente = 0)
		SET @ORDER = @ORDER + ' DESC'
	ELSE
		SET @ORDER = @ORDER + ' ASC'

	SET @SCRIPT = 'SELECT ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS ORDER BY'
	
	SET @SCRIPT = @SCRIPT + @ORDER
			
	EXECUTE SP_EXECUTESQL @SCRIPT

	SELECT COUNT(1) FROM BENEFICIARIOS WITH(NOLOCK)
END